name: Python CI

on:
  push:
    branches: ["main", "feature/lab11"]
  pull_request:
    branches: ["main", "feature/lab11"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        # Le indicamos explícitamente a este paso dónde encontrar requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r alpha-beta-lab/requirements.txt

      - name: Run tests with coverage
        # Le indicamos a pytest que se ejecute posicionándose dentro de la subcarpeta
        working-directory: alpha-beta-lab
        run: |
          pytest --cov=src --cov-report=xml --cov-report=term-missing